### ISSUE TITLE
Parse error when running checksetup.pl

### ISSUE THREAD

**Issue by devzing** [repeat/bugzilla-tw#16]
When I run checksetup.pl I always get this error:

Removing existing compiled templates...
Precompiling templates...file error - parse error - bug/show-multiple.html.tmpl line 369: unexpected end of input

Bugzilla 5.0.3
zh-TW from v5.0.3 tag

**Comment by devzing** [comment]
Fixing the errors identified by fz0000 fixes this issue.

**Comment by repeat** [comment]
Fixed in [v5.0.3+p1](https://github.com/repeat/bugzilla-tw/releases/tag/v5.0.3%2Bp1) & [v5.1.1+p1](https://github.com/repeat/bugzilla-tw/releases/tag/v5.1.1%2Bp1).
