### ISSUE TITLE
汉化为简体中文

### ISSUE THREAD

**Issue by James6xie** [repeat/bugzilla-tw#24]
Hi 你好！
  我想汉化为简体中文，想知道汉化流程和方法，提前谢谢您。

**Comment by fz0000** [comment]
bugzilla的官方文档里面有说明：
[https://bugzilla.readthedocs.io/en/latest/integrating/templates.html#template-directory-structure](https://bugzilla.readthedocs.io/en/latest/integrating/templates.html#template-directory-structure)
简单来说就从官网下载最新版本代码后将下面的template\en文件夹复制一份到template\zh-cn，然后翻译里面的tmpl文件就行。

**Comment by vincentdd** [comment]
遇到个问题请教下，我下了汉化包之后浏览器打开就乱码了，要手动把浏览器的编码格式改成gb2312来解析就能正确显示中文了，但是非常麻烦，每次打开一个页面都要这样手动切换。我看了所有的模板文件都是ut-f8格式的，想问下这是什么问题，是哪里的编码格式设置不对吗
